### ISSUE TITLE
Unity TODO 📝

### ISSUE THREAD

**Issue by dunnkers** [jorispdejong/GeneticAlgorithm#1]
- [x] 💡 Use a library like [CsvHelper](https://joshclose.github.io/CsvHelper/) to parse CSV instead of doing it yourself?

Extensions (ideas):
- [x] On/off button for visualising coordinates
   - [x] Coordinates next to ball
- [x] Slider for animation speed of ball
